name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: bun today.js

      - name: Commit new images
        run: |-
          git add .
          git diff
          git config --global user.email "kellenberg.kevin@gmail.com"
          git config --global user.name "zxmpg41/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
